FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /src
COPY ["src/PizzaWeb.Api/PizzaWeb.Api.csproj", "PizzaWeb.Api/"]
RUN dotnet restore "PizzaWeb.Api/PizzaWeb.Api.csproj" -r linux-musl-x64 /p:PublishReadyToRun=true
COPY . .
WORKDIR "/src/PizzaWeb.Api"
# RUN dotnet build "PizzaWeb.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PizzaWeb.Api.csproj" --no-restore -c Release -o /app/publish -r linux-musl-x64 --self-contained true /p:PublishTrimmed=false

FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["./PizzaWeb.Api"]
